# Generated by Django 5.0.2 on 2024-03-11 03:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Taxi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("plate", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Trajectory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(default=datetime.datetime.now)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("taxi", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="taxis.taxi")),
            ],
        ),
    ]
